### ISSUE TITLE
Adding an icon to a menu item makes onSelect stop working

### ISSUE THREAD

**Issue by rsweeney21** [grail-ui/grail-ui#124]
To create the repro I forked the example at https://grail-ui.vercel.app/svelte/menu and changed

```<li><a href="/" {...$itemAttrs('edit')}>Edit</a></li>```

to

```<li><a href="/" {...$itemAttrs('edit')}><span>icon</span>Edit</a></li>```

Repro: https://stackblitz.com/edit/angular-lzm7r6?file=src/routes/+page.svelte

Repro steps
1. Open the stack blitz
2. Click "Menu"
3. Click on "icon" in the Edit menu item.

Expected
onSelected is called and an alert is shown.

Actual
Nothing happens.

It looks like onSelect only fires if the click event happens directly on the button or anchor. If you include any other elements in the button content, or wrap the content in a span, the click event is ignored.

**Comment by bekos** [comment]
@rsweeney21 Fixed has been released in v0.9.2 Please check again and re-open in case things don't work as expected.
