### ISSUE TITLE
[Feature Request] Tabs need ability to Load on Demand

### ISSUE THREAD

**Issue by NathanaelA** [grail-ui/grail-ui#134]
The Grail-UI project looks like a pretty cool project.    I was looking at your Tab-UI stuff because I currently maintain my own tab ui library, but it would be nice if it was something I could eliminate because of better library.  

However, the Grail-UI Tabs component loads all tab content by default.    This is very much a massive performance issue when you have complex data in each tab.  

Screen shot from the GradleUI site showing all the content loaded by default...
![image](https://github.com/grail-ui/grail-ui/assets/850871/fa079699-96ff-4382-9a05-b0c4b90b695b)

I use tabs in my Launcher.
![image](https://github.com/grail-ui/grail-ui/assets/850871/addc93fb-584c-4fd2-9250-4a91f5603e65)

In my launcher, the Marketplace and Fab tabs, are both very heavy web pages.     The assets tab is over 600 images in a grid.    Not to mention the other tabs.   If all that is loading when the main page is instantiated, it makes the app very sluggish on startup.       In my Tab code, I added code to allow tabs to be loaded on demand.     So when you click those tabs, the content is  then loaded and then added to the DOM.   Small tabs I let default to being added at runtime, but heavy tab's I tag as load-on-demand.

**Comment by bekos** [comment]
hi @NathanaelA 🙂 first of all thx for your kind words 🙂 

you can leverage the `active` store in the same way that we activate the appopriate tab header, in order to display or not your content. So something like this:

<img width="555" alt="image" src="https://github.com/grail-ui/grail-ui/assets/551595/6a48fd04-2cb3-4746-8215-7f479cf8eb5a">

I think this solves your issue but feel free to re-open it's not. Thx again.

**Comment by NathanaelA** [comment]
Hmm,  the only reason I was suggesting it is handled internally is because if I've already loaded the tab into the DOM, then I also leave it in the DOM but just hide it, this eliminate rebuilds especially on heavy tabs. 

In your example  you are destroying the prior tab on each tab change, and then re-creating the new one.       I realize I can create my own state handling code to handle has it been shown before, just imho, makes more sense for the tab handling code to handle all the state stuff for a tab rather than me having to manage it externally.
