### ISSUE TITLE
Menu Component Keyboard Selection Issue

### ISSUE THREAD

**Issue by fleq6** [grail-ui/grail-ui#143]
When the list items of a menu component contain anchor tags, and the menu item attributes are given to the anchor tags, just like the example in the official documentation, menu items are selectable with the keyboard.

However, when this pattern is not followed, keyboard selection stops working.

For example, in this repro there are no anchor tags, the menu item attributes are on the list item tags.
https://stackblitz.com/edit/zfttmz?file=src%2Froutes%2F%2Bpage.svelte

**Comment by bekos** [comment]
@fleq6 can you verify that your issue is fixed?

**Comment by fleq6** [comment]
@bekos Yes, I can confirm it's fixed!
Thank you.
